name: Backup db

on:
  schedule:
    - cron: '5 * * * *'

jobs:
  backup:
    runs-on: [self-hosted, nft-marketplace]
    steps:
    - name: Create dirs
      run: |
        cd ~
        mkdir -p nft-marketplace/backups/db || true
    - name: Make backup
      run: |
        cd ~/nft-marketplace/backups/db
        docker exec nft-marketplace-prod-db-1 pg_dump -U user db -Fc | lzma -9e --threads=0 > $(date +"%Y-%m-%dT%H:%M:%S")
    - name: Clean old backups
      run: |
        cd ~/nft-marketplace/backups/db
        ls -t | sed -e '1,5d' | xargs rm -rf
