name: "Call: CI"

on:
  workflow_call:
  workflow_dispatch:

jobs:
  lint:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3.1.0
      - uses: actions/setup-python@v4.3.0
        with:
          python-version: 3.10.8
      - name: Run pre-commit
        uses: pre-commit/action@v3.0.0
  test:
    runs-on: [ self-hosted, nft-marketplace ]
    steps:
      - run: cd ..
      - uses: actions/checkout@v3.1.0
        with:
          clean: false
          path: nft-marketplace-test
      - name: Run tests
        run: docker-compose -f docker/test/docker-compose.test.yml -p nft-marketplace-test up --build api
      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v3.1.1
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          files: ./coverages/coverage.xml
