name: Cd

on:
  push:
    branches: [ "master" ]

jobs:
  deploy_dev:
    runs-on: self-hosted
    steps:
    - uses: actions/checkout@v3
    - name: Deploy dev environment
      run: docker-compose -f docker/docker-compose.dev.yml up --force-recreate --build -d
