name: "PR: add assignees"

on:
  pull_request:
    types: opened

permissions:
  pull-requests: write

jobs:
  add:
    runs-on: ubuntu-22.04
    steps:
      - uses: kentaro-m/auto-assign-action@v1.2.4
